env:
  TERM: xterm-256color

background_opacity: 0.85

window:
  decorations: full
  startup_mode: Maximized
  dynamic_title: true
  padding:
    x: 2
    y: 2
  dynamic_padding: true

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: JetBrains Mono
    style: Regular

  # The bold font face
  bold:
    family: JetBrains Mono
    style: Bold

  # The italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  # Point size of the font
  size: 11.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

colors:
  # Default colors
  primary:
    background: '0x111111'
    foreground: '0xeeeeee'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x020221'
    cursor: '0xffe8c0'

  # Normal colors
  normal:
    black:   '0x000004'
    red:     '0xff3600'
    green:   '0x718e3f'
    yellow:  '0xffc552'
    blue:    '0x635196'
    magenta: '0xff761a'
    cyan:    '0x34bfa4'
    white:   '0xb4b4b9'

  # Bright colors
  bright:
    black:   '0x020221'
    red:     '0xff8e78'
    green:   '0xb1bf75'
    yellow:  '0xffd392'
    blue:    '0x99a4bc'
    magenta: '0xffb07b'
    cyan:    '0x8bccbf'
    white:   '0xf8f8ff'

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

mouse:
  hide_when_typing: true
# vim: ft=yaml ts=2 sw=2 et
