set -g mouse on
setw -g mode-keys vi

set -g set-titles on
set -g set-titles-string "#T"
if-shell 'test -n "$SSH_CONNECTION"' \
    'set -g set-titles-string "[ssh #h] #T"'

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
