set -g mouse on
setw -g mode-keys vi
set -g focus-events on
set -g extended-keys on
# set -g extended-keys-format csi-u

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g set-titles on
set -g set-titles-string "#T"
if-shell 'test -n "$SSH_CONNECTION"' \
    'set -g set-titles-string "[ssh #h] #T"'

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
