[colors]
background = #000000
background-alt = #373B41
foreground = #CCCCCC
primary = #F0C674
secondary = #8ABEB7
success = #00FF00
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font:size=12;2

modules-left = launcher xwindow
modules-right = wlan pulseaudio backlight cpu memory battery date caffeine

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/launcher]
type = custom/text
content = " 󰖌"
content-foreground = ${colors.primary}
content-padding = 0
click-left = rofi -show drun
click-right = rofi -show window

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage:03%%

label-muted = 󰖁 muted
label-muted-foreground = ${colors.disabled}

click-right = pavucontrol

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
format = <label>
format-prefix = "󰃞 "
format-prefix-foreground = ${colors.primary}
label = %{A4:brightnessctl set +1%:}%{A5:brightnessctl set 1%-:}%percentage:03%%%{A}%{A}

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = "C "
format-prefix-foreground = ${colors.primary}
label = %percentage:03%%

[module/memory]
type = internal/memory
interval = 5
format-prefix = "M "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:03%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}󱚵 %ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:alacritty -e nmtui:}%{F#F0C674}󰖩 %ifname%%{F-} %essid% %local_ip%%{A}
label-disconnected = %{A1:alacritty -e nmtui:}%{F#F0C674}󱚵 %ifname%%{F#707880} disconnected%{A}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98
low-at = 15
poll-interval = 5

format-charging = %{A1:gnome-power-statistics:}<animation-charging> <label-charging>%{A}
label-charging = %percentage:03%% %time%

format-discharging = %{A1:gnome-power-statistics:}<ramp-capacity> <label-discharging>%{A}
label-discharging = %percentage:03%% %time%

format-full = %{A1:gnome-power-statistics:}<ramp-capacity> <label-full>%{A}
label-full =  %percentage:03%%

format-low = %{A1:gnome-power-statistics:}<ramp-capacity> <label-low>%{A}
label-low = %percentage:03%%

time-format = %H:%M

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁼
ramp-capacity-2 = 󰁾
ramp-capacity-3 = 󰂀
ramp-capacity-4 = 󰁹
ramp-capacity-0-foreground = #f53c3c
ramp-capacity-1-foreground = ${colors.primary}
ramp-capacity-2-foreground = ${colors.primary}
ramp-capacity-3-foreground = ${colors.primary}
ramp-capacity-4-foreground = ${colors.primary}

animation-charging-0 = 󰢜
animation-charging-1 = 󰂆
animation-charging-2 = 󰂈
animation-charging-3 = 󰂉
animation-charging-4 = 󰂋
animation-charging-5 = 󰂅
animation-charging-foreground = ${colors.success}
animation-charging-framerate = 1000

[module/date]
type = internal/date
interval = 1
format =  <label>
format-foreground = ${colors.primary}
date = %H:%M:%S
date-alt = %a %Y-%m-%d %H:%M:%S
label =  %date%
label-foreground = ${colors.foreground}

[module/caffeine]
type = custom/ipc
initial = 1
hook-0 = caffeine.sh | grep -q on && echo "%{F#F0C674}󰛊%{F-}" || echo "%{F#707880}󰛊%{F-}"
click-left = caffeine.sh toggle

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
