# 3-finger swipe = ganti workspace Openbox
gesture swipe right 3 xdotool key ctrl+alt+Left
gesture swipe left 3 xdotool key ctrl+alt+Right

# 4-finger swipe = show desktop
gesture swipe up 4 wmctrl -k on

# Pinch = zoom (di browser misalnya)
gesture pinch in xdotool key ctrl+minus
gesture pinch out xdotool key ctrl+plus
