"" General
""----------------------------------------------------------------------------

set nocompatible

set history=500
set mouse=a
set ttyfast
set lazyredraw
set timeoutlen=1000
set ttimeoutlen=0
set noerrorbells

set title
set relativenumber
set number
"set cursorline
set scrolloff=3
set colorcolumn=80,120
set signcolumn=yes

set nowrap
set encoding=utf-8 nobomb
set nostartofline

set autoread
set nobackup
set nowb
set noswapfile
set hidden

set backspace=indent,eol,start
set autoindent
set smartindent

set listchars=tab:▏\ ,trail:·
"set listchars=tab:▏·,space:·
set list

set hlsearch
set incsearch
set wildmenu
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.psd
set wildignore+=*.pdf
set wildignore+=.DS_Store
set wildignore+=.git/*,node_modules/*,bower_components/*
set synmaxcol=2500

" set t_Co=256 " is a bad idea, set your terminal up properly instead.
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
set background=dark
set showmatch
set noshowmode
set showtabline=2
set guioptions-=e
set laststatus=2

" Use system clipboard -  http://vim.wikia.com/wiki/Accessing_the_system_clipboard
let uname = substitute(system('uname'), '\n', '', '')
if uname == 'Darwin'
	set clipboard=unnamed " for macOS
elseif uname == 'Linux'
	set clipboard=unnamedplus " for linux
endif

filetype plugin indent on
syntax on

if !has('nvim')
	packadd! matchit
endif

call plug#begin('~/.vim/plugged')

Plug 'gruvbox-community/gruvbox'

Plug 'mengelbrecht/lightline-bufferline'
Plug 'itchyny/lightline.vim'
Plug 'shinchu/lightline-gruvbox.vim'
"Plug 'nathanaelkane/vim-indent-guides'
"
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-rooter'

Plug 'editorconfig/editorconfig-vim'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'junegunn/vim-easy-align', {'on': '<plug>(LiveEasyAlign)'}
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'Yggdroot/indentLine'

Plug 'dense-analysis/ale'
Plug 'pangloss/vim-javascript'
Plug 'jonsmithers/vim-html-template-literals'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE

augroup theme
	autocmd!
	autocmd VimEnter * ++nested colorscheme gruvbox
	autocmd VimEnter * ++nested hi Normal guibg=NONE ctermbg=NONE
augroup end

let g:gruvbox_transparent_bg = 1
let g:gruvbox_contrast_dark = 'hard'

let g:netrw_banner = 0
let g:netrw_winsize = 30
let g:netrw_liststyle = 3
let g:netrw_dirhistmax = 0
let g:netrw_browse_split = 4
let g:netrw_altv = 1

let g:lightline = {
	\ 'colorscheme': 'gruvbox',
	\ 'tabline': {'left': [['buffers']], 'right': [['']]},
	\ 'component_expand': {'buffers': 'lightline#bufferline#buffers'},
	\ 'component_type': {'buffers': 'tabsel'}
	\ }
let g:lightline.separator = {'left': '', 'right': ''}
let g:lightline.subseparator = {'left': '', 'right': ''}
let g:lightline#bufferline#show_number = 1
let g:lightline#bufferline#unnamed = '[noname]'

let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1 " Status line types/signatures.

let g:ale_sign_error = '●'
let g:ale_sign_warning = '●'

let g:indentLine_char = '▏'

"" Bind keys
""----------------------------------------------------------------------------

let mapleader=','

nnoremap Y y$

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

nnoremap <silent> <C-J> :<C-U>m .+1<CR>==
nnoremap <silent> <C-K> :<C-U>m .-2<CR>==
inoremap <silent> <C-J> <Esc>:m .+1<CR>==gi
inoremap <silent> <C-K> <Esc>:m .-2<CR>==gi
vnoremap <silent> <C-J> :m '>+1<CR>gv=gv
vnoremap <silent> <C-K> :m '<-2<CR>gv=gv

nnoremap <silent> <Leader>p :<C-U>Files<CR>
nnoremap <silent> <Leader>b :<C-U>Buffers<CR>
nnoremap <silent> <Leader>e :<C-U>Lex!<CR>
nnoremap <silent> <Leader>w :<C-U>w<CR>
inoremap <silent> <Leader>w <ESC>:w<CR>
inoremap <silent> <Leader>q <ESC>:q!<CR>
nnoremap <silent> <Leader>q :<C-U>q!<CR>

nnoremap <silent> <C-L> :<C-U>let @/ = "" <Bar> nohl<CR><C-L>

nnoremap g/ :<C-U>%s//g<Left><Left>

function! ChangeBuffer(count) abort
	if a:count ==# 0
		silent! execute 'bnext'
	else
		silent! execute 'buffer ' . a:count
	endif
endfunction

command! -nargs=1 ChangeBufferCmd call ChangeBuffer(<args>)
nnoremap <silent> gb :<C-U>ChangeBufferCmd(v:count)<CR>
nnoremap <silent> gB :<C-U>bprev<CR>

nnoremap <silent> [a :<C-U>ALEPreviousWrap<CR>
nnoremap <silent> ]a :<C-U>ALENextWrap<CR>

imap <C-C> <ESC>

augroup CursorOnInsert
	autocmd!
	autocmd InsertEnter * set cursorline
	autocmd InsertLeave * set nocursorline
augroup end
