small: &small JetBrainsMono Nerd Font:pixelsize=16

# This is THE bar configuration
bar:
  location: top
  height: 22
  spacing: 0
  margin: 0
  font: JetBrainsMono Nerd Font:pixelsize=16
  foreground: ffffffff
  # background: 00000000
  # background: 000000ff
  # background: 66333366
  background: 111111ff

  # border:
  #   width: 0
  #   bottom-width: 1
  #   color: 666666cc
  #   # color: 660000ff
  #   margin: 0

  left:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: " 󰘔 {app-id}"}
                - string: {text: "  "}
                - string: {text: "{title}"}
                - string: {text: "  "}

  # center:
  right:
    - network:
        name: en1
        content:
          - string: {text: "  "}
          - map:
              default: {empty: {}}
              conditions:
                name == en1 && carrier:
                  - map:
                      default: {string: {text: " 󰈀 - ", foreground: ffffff66}}
                      conditions:
                        state == up && ipv4 != "": {string: {text: " 󰈀 {ipv4} "}}
                  - string: {text: "  "}

    - network:
        name: wlo1
        content:
          - map:
              default: {empty: {}}
              conditions:
                name == wlo1:
                  map:
                    on-click: foot nmtui
                    default: {string: {text: " 󰤨 down ", foreground: ffffff66}}
                    conditions:
                      state == down: {string: {text: " 󰤮 down ", foreground: ff0000ff}}
                      state == up:
                        map:
                          default:
                            - string: {text: " 󰤨 {ssid} {ipv4} "}
                          conditions:
                            ipv4 == "":
                              - string: {text: " 󰤨 {ssid} - ", foreground: ffffff66}
          - string: {text: "  "}

    - script:
        path: ~/bin/systower
        args: ["watch"]
        content:
          # Vol
          - map:
              on-click: pavucontrol
              default:
                - string: {text: " 󰕾 {vol_percent}% "}
              conditions:
                vol_muted:
                  - string: {text: " 󰝟 {vol_percent}% ", foreground: ff0000ff}
                vol_percent == 0:
                  - string: {text: " 󰖁 {vol_percent}% "}
                vol_percent < 70:
                  - string: {text: " 󰖀 {vol_percent}% "}
                vol_percent > 100:
                  - string: {text: " 󰕾 {vol_percent}% ", foreground: ffff00ff}
          - string: {text: "  "}
          # Backlight
          - string: {text: " 󰃠 {backlight_percent}% "}
          - string: {text: "  "}
          # CPU
          - map:
              on-click: foot htop
              default:
                - string: {text: " 󰍛 {cpu_percent:.1}% "}
              conditions:
                cpu_percent >= 75:
                  - string: {text: " 󰍛 {cpu_percent:.1}% ", foreground: ff0000ff}
                cpu_percent >= 50:
                  - string: {text: " 󰍛 {cpu_percent:.1}% ", foreground: ffff00ff}
          - string: {text: "  "}
          # Memory
          - map:
              on-click: foot htop
              default:
                - string: {text: " 󰘚 {mem_used:.1}GB "}
              conditions:
                mem_percent >= 90:
                  - string: {text: " 󰘚 {mem_used:.1}GB ", foreground: ff0000ff}
                mem_percent >= 60:
                  - string: {text: " 󰘚 {mem_used:.1}GB ", foreground: ffff00ff}
          - string: {text: "  "}
          # Disk
          - map:
              default:
                - string: {text: " 󰋊 {storage_percent:.1}% "}
              conditions:
                storage_percent >= 90:
                  - string: {text: " 󰋊 {storage_percent:.1}% ", foreground: ff0000ff}
                storage_percent >= 75:
                  - string: {text: " 󰋊 {storage_percent:.1}% ", foreground: ffff00ff}
          - string: {text: "  "}
          # Battery
          - map:
              on-click: gnome-power-statistics
              default:
                - string: {text: " 󰁹 {bat_percent}%"}
              conditions:
                bat_status == "full":
                  - string: {text: " 󰁹 {bat_percent}%", foreground: 00ff00ff}
                bat_status == "charging" && bat_percent >= 95:
                  - string: {text: " 󰂄 {bat_percent}%", foreground: 00ff00ff}
                bat_status == "charging":
                  - string: {text: " 󰂄 {bat_percent}%"}
                bat_percent <= 15:
                  - string: {text: " 󰂎 {bat_percent}%", foreground: ff0000ff}
                bat_percent <= 50:
                  - string: {text: " 󰁾 {bat_percent}%", foreground: ffff00ff}
          - map:
              default: {empty: {}}
              conditions:
                bat_estimate != "":
                  - string: {text: " {bat_estimate}"}
          # Caffeine
          - map:
              on-click: ~/bin/systower caffeine toggle
              conditions:
                caffeine == "on":
                  - string: {text: " 󰅶 ", foreground: 00ff00ff}
                caffeine == "off":
                  - string: {text: " 󰅶 "}
          - string: {text: "  "}
          # Clock
          - map:
              on-click: orage --toggle
              default:
                - string: {text: " 󰔠 {clock_date} {clock_time} "}
              conditions: {}
